### ISSUE TITLE
Remove Collibra Connect/domain apps from deployment

### ISSUE THREAD

**Issue by jrgarner** [plus3it/cfn-collibra#18]
### Problem Description:

No longer need the Collibra Connect domain and connector application installed on the Mule ESB server. Remove parameters, and stop installation

### Expected Behavior:

No need to provide parameter values

### Actual Behavior:

Parameters still requested

### (Detailed) Steps to reproduce:

Run 15_Collibra_ESB_Server pipeline

**Comment by ferricoxide** [comment]
Cool. I'll try to tackle that, tomorrow.
