### ISSUE TITLE
ESB template failure

### ISSUE THREAD

**Issue by jrgarner** [plus3it/cfn-collibra#24]
### Problem Description:

ESB template still calls for MuleConnectorZipUri, MuleDomainZipUri values

### Expected Behavior:

These values were supposed to be removed, since they are no longer needed.

### Actual Behavior:

Template errors out calling for values.

Error text: 
An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [MuleConnectorZipUri, MuleDomainZipUri] must have values

### (Detailed) Steps to reproduce:

Run 15_Collibra_ESB_Server pipeline

**Comment by ferricoxide** [comment]
Can't reproduce
* They were removed in 163cb38b2f9b25b2aa8fec5829b370bc3f804ff0
* Can't find those references in repository

    ~~~~
    $ find cfn-collibra -type f -name "*.tmplt.json" -o -name "*.groovy" | \
    xargs grep -E "(MuleDomainZipUri|MuleConnectorZipUri)"
    ~~~~

Are you sure you're using an up-to-date copy of the code?

**Comment by ferricoxide** [comment]
Looked at your Jenkins job: your `TemplateUrl` job-parameter was pointing to an out-of-date copy of the template. Updated the S3 bucket contents. The `replay` of your job appears to be running fine with the updated S3 content.

Would mark this `NOTABUG` if I had that label set up in this project. For now, this is "pending-close"
